# Generated by Django 2.0.6 on 2018-07-22 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subtitle_app', '0008_suggestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestion',
            name='trans_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
