# Generated by Django 2.0.6 on 2018-07-22 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subtitle_app', '0009_suggestion_trans_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suggestion',
            name='count',
        ),
        migrations.RemoveField(
            model_name='suggestion',
            name='probability',
        ),
    ]
