# Generated by Django 2.0.6 on 2018-08-02 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subtitle_app', '0011_translate_edit_translation'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=250, null=True)),
                ('time', models.CharField(blank=True, max_length=250, null=True)),
                ('document', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='subtitle_app.Document')),
            ],
        ),
    ]
